import MI32

#print axioms MI32.moment_zero
#print axioms MI32.weakMoment_univ
#print axioms MI32.spectralNorm_eq_l2_operator
#print axioms MI32.first_deletion_exponent
#print axioms MI32.moment_nat_pow
#print axioms MI32.integral_pow_doubling
#print axioms MI32.PositivePolynomial.tensorMoment_add_le
#print axioms MI32.PositivePolynomial.positive_sum_second_moment_le
#print axioms MI32.PositivePolynomial.integrable_monomial
#print axioms MI32.PositivePolynomial.integral_evaluate_sq_le
#print axioms MI32.PositivePolynomial.moment_add_le_of_doubling
#print axioms MI32.PositivePolynomial.integral_evaluate_sq_le_of_doubling
#print axioms MI32.positive_polynomial_second_moment_of_regular
#print axioms MI32.fourth_sum_squares_le
#print axioms MI32.hilbert_walsh_fourth_le
#print axioms MI32.ParityGeometry.multiplicationEntry_eq_creation_add_annihilation
#print axioms MI32.ParityGeometry.creationEntry_eq_grade_compression
#print axioms MI32.ParityGeometry.annihilationEntry_eq_grade_compression
#print axioms MI32.ParityGeometry.creationApply_eq_label_sum
#print axioms MI32.ParityGeometry.annihilationApply_eq_label_sum
#print axioms MI32.ParityGeometry.creationGram_eq_zero_of_rowCount_ne
#print axioms MI32.PositiveCone.evaluate_energy
#print axioms MI32.PositiveCone.walsh_second_eq_energy
#print axioms MI32.PositiveCone.integrated_walsh_fourth_le
#print axioms MI32.positive_cone_fourth_moment_of_regular
#print axioms MI32.RawParity.parity_card_le_degree
#print axioms MI32.RawParity.monomial_sign
#print axioms MI32.RawParity.evaluate_sign_eq_cutoff
#print axioms MI32.RawParity.parity_add
#print axioms MI32.raw_positive_polynomial_fourth_moment
#print axioms MI32.ConeInterpolation.moment_holder_order_le
#print axioms MI32.ConeInterpolation.moment_four_q_le
#print axioms MI32.ConeInterpolation.memLp_of_fourth
#print axioms MI32.SymmetricLaw.map_signedAbs_eq
#print axioms MI32.SymmetricLaw.map_independent_signedAbs_eq_original
#print axioms MI32.SymmetricLaw.integral_eq_walsh_signedAbs
#print axioms MI32.SymmetricLaw.independent_abs
#print axioms MI32.exists_half_net
#print axioms MI32.opNorm_le_two_of_half_net
#print axioms MI32.opNorm_pow_le_net_sum
#print axioms MI32.integral_opNorm_pow_le_of_images
#print axioms MI32.integral_linear_sum_sq
#print axioms MI32.integral_matrix_image_sq
#print axioms MI32.integral_matrix_image_sq_le
#print axioms MI32.matrixRowImage_norm_sq
#print axioms MI32.integral_matrixRowImage_norm_le
#print axioms MI32.SymmetricPositiveCone.integrable_normSq
#print axioms MI32.SymmetricPositiveCone.integrable_normSq_sq
#print axioms MI32.SymmetricPositiveCone.fourth_moment
#print axioms MI32.SymmetricPositiveCone.fourth_norm_moment
#print axioms MI32.PositiveLinearPowers.wordExponent_degree
#print axioms MI32.PositiveLinearPowers.evaluate_words
#print axioms MI32.PositiveLinearPowers.signed_linear_even_moment_doubling_real_coeff
#print axioms MI32.PositiveLinearPowers.signed_linear_even_root_doubling
#print axioms MI32.PositiveMomentComparison.integral_evaluate_le_of_moments
#print axioms MI32.SymmetricMomentComparison.integral_odd_power_eq_zero
#print axioms MI32.SymmetricMomentComparison.sum_even_power_le
#print axioms MI32.SymmetricMomentComparison.sum_even_moment_le_of_coordinate_moments
#print axioms MI32.CopySymmetrization.centered_even_moment_le_copy
#print axioms MI32.HilbertConditioning.integral_inner_pow_le_of_unit
#print axioms MI32.HilbertConditioning.integral_copy_inner_pow_le
#print axioms MI32.IndependentColumns.independent_column_vectors
#print axioms MI32.IndependentColumns.independent_columnLinearForm
#print axioms MI32.IndependentColumns.symmetric_columnLinearForm
#print axioms MI32.IndependentColumns.integrable_abs_rpow_columnLinearForm
#print axioms MI32.IndependentColumns.integral_columnLinearForm_eq_zero
#print axioms MI32.DiagonalCopyComparison.independent_coordinatePairs
#print axioms MI32.DiagonalCopyComparison.independent_squareDifferences
#print axioms MI32.DiagonalCopyComparison.independent_copyProducts
#print axioms MI32.DiagonalCopyComparison.symmetric_squareDifference
#print axioms MI32.DiagonalCopyComparison.symmetric_copyProduct
#print axioms MI32.DiagonalCopyComparison.integrable_copyProduct_pow
#print axioms MI32.DiagonalCopyComparison.integrable_squareDifference_pow
#print axioms MI32.DiagonalCopyComparison.coordinate_even_moment_le_nat
#print axioms MI32.MomentTools.memLp_of_integrable_abs_rpow
#print axioms MI32.MomentTools.memLp_square
#print axioms MI32.MomentTools.add_le
#print axioms MI32.MomentTools.mono_exponent
#print axioms MI32.MomentTools.square
#print axioms MI32.MomentTools.two_order_square_le_mean_add_centered_square
#print axioms MI32.MomentTools.even_moment_le_of_integral_le
#print axioms MI32.SymmetricLinearRegularity.linear_even_root_doubling
#print axioms MI32.SymmetricLinearRegularity.columnLinearForm_even_root_doubling
#print axioms MI32.HilbertComparison.independent_coordinate_moment_le
#print axioms MI32.ThinMomentRoot.opNorm_moment_le_of_images
#print axioms MI32.ThinMomentRoot.opNorm_moment_four_mul_le_of_images
#print axioms MI32.SymmetricConeInterpolation.moment_holder_order_le
#print axioms MI32.SymmetricConeInterpolation.moment_four_q_le

-- Original-law thin actions, exact raw sectors, and their contractions.
#print axioms MI32.ActiveCountSectors.annihilation_support_card_le
#print axioms MI32.ActiveCountSectors.annihilation_support_card_le_of_coeff_ne_zero
#print axioms MI32.ActiveCountSectors.creation_evaluate_eq_zero
#print axioms MI32.ActiveCountSectors.creation_maskCoeff_eq_zero
#print axioms MI32.ActiveCountSectors.creation_support_card_le
#print axioms MI32.ActiveCountSectors.creation_support_card_le_of_coeff_ne_zero
#print axioms MI32.AnnihilationSectorContraction.inputCoeff_eq_zero_of_support_card_gt
#print axioms MI32.AnnihilationSectorContraction.input_polynomial_eq_zero
#print axioms MI32.AnnihilationSectorContraction.sectorAction_eq_zero
#print axioms MI32.AnnihilationSectorContraction.sectorAction_l2_le
#print axioms MI32.AxisRestriction.bilinear_restrict_axes
#print axioms MI32.AxisRestriction.moment_restrict_axes
#print axioms MI32.AxisRestriction.norm_zeroExtend
#print axioms MI32.AxisRestriction.thin_weak_test_restrict_cols
#print axioms MI32.AxisRestriction.thin_weak_test_restrict_rows
#print axioms MI32.AxisRestriction.thin_weak_test_transposed_cols
#print axioms MI32.AxisRestriction.transposeOperator_restrict_rows
#print axioms MI32.AxisRestriction.weak_test_restrict_axes
#print axioms MI32.AxisRestriction.zeroExtendIsometry
#print axioms MI32.CreationSectorContraction.sectorAction_l2_le
#print axioms MI32.MaskedPolynomialAction.evaluateHilbert_extend_eq_action
#print axioms MI32.MaskedPolynomialAction.maskedAction_moment_le
#print axioms MI32.MultiplicationHolder.dominated_product_moment_le
#print axioms MI32.MultiplicationHolder.operator_action_l2_le
#print axioms MI32.MultiplicationHolder.product_moment_le
#print axioms MI32.OutputPolynomialInteraction.action_l2_le
#print axioms MI32.OutputPolynomialInteraction.measurable_action
#print axioms MI32.OutputPolynomialInteraction.same_entries_action_l2_le
#print axioms MI32.ParityWalshCompression.annihilationApply_L2_le
#print axioms MI32.ParityWalshCompression.annihilationApply_eq_grade_compression
#print axioms MI32.ParityWalshCompression.annihilationApply_eq_inputSectorMask
#print axioms MI32.ParityWalshCompression.annihilationApply_eq_sector_grade_compression
#print axioms MI32.ParityWalshCompression.coefficient_eq_creation_add_annihilation
#print axioms MI32.ParityWalshCompression.coefficient_finiteMatrixApply
#print axioms MI32.ParityWalshCompression.coefficient_matrixApply
#print axioms MI32.ParityWalshCompression.creationApply_L2_le
#print axioms MI32.ParityWalshCompression.creationApply_eq_grade_compression
#print axioms MI32.ParityWalshCompression.creationApply_eq_inputSectorMask
#print axioms MI32.ParityWalshCompression.creationApply_eq_sector_grade_compression
#print axioms MI32.ParityWalshCompression.finiteMatrixApply_eq_matrixApply
#print axioms MI32.ParityWalshCompression.finiteMatrixApply_eq_polynomial_coeff
#print axioms MI32.ParityWalshCompression.finiteMatrixApply_parseval
#print axioms MI32.ParityWalshCompression.inputMask_L2_contraction
#print axioms MI32.ParityWalshCompression.inputPolynomial_parseval
#print axioms MI32.ParityWalshCompression.outputMask_L2_contraction
#print axioms MI32.PolynomialSectorEnergy.conditional_disjoint_mask_inner_eq_zero
#print axioms MI32.PolynomialSectorEnergy.integrable_conditionalEnergy
#print axioms MI32.PolynomialSectorEnergy.integrable_original_norm_sq
#print axioms MI32.PolynomialSectorEnergy.integrable_polynomial_inner
#print axioms MI32.PolynomialSectorEnergy.integral_disjoint_mask_inner_eq_zero
#print axioms MI32.PolynomialSectorEnergy.integral_norm_sq_eq_conditionalEnergy
#print axioms MI32.PolynomialSectorEnergy.masked_second_energy_le
#print axioms MI32.PolynomialSectorEnergy.sum_sector_second_energies
#print axioms MI32.PolynomialSectorMasks.conditionalEnergy_mask_le
#print axioms MI32.PolynomialSectorMasks.maskCoeff_comp
#print axioms MI32.PolynomialSectorMasks.maskCoeff_nonneg
#print axioms MI32.PolynomialSectorMasks.sectionCoeff_mask
#print axioms MI32.PolynomialSectorMasks.sum_conditionalEnergy_sectors
#print axioms MI32.PositiveWordExtension.degree_extendExponent
#print axioms MI32.PositiveWordExtension.evaluate_extend
#print axioms MI32.PositiveWordExtension.evaluate_linearExtend
#print axioms MI32.PositiveWordExtension.evaluate_masked_extend
#print axioms MI32.PositiveWordExtension.masked_extension_comp
#print axioms MI32.PositiveWordExtension.masked_extension_positive_degree
#print axioms MI32.PositiveWordExtension.masked_linearExtension_positive_degree
#print axioms MI32.PositiveWordExtension.parity_extendExponent
#print axioms MI32.RawCountBlocks.annihilation_count_block
#print axioms MI32.RawCountBlocks.annihilation_full_block
#print axioms MI32.RawCountBlocks.annihilation_grade_compression
#print axioms MI32.RawCountBlocks.annihilation_output_mask_invariant
#print axioms MI32.RawCountBlocks.creation_count_block
#print axioms MI32.RawCountBlocks.creation_full_block
#print axioms MI32.RawCountBlocks.creation_grade_compression
#print axioms MI32.RawCountBlocks.creation_output_mask_invariant
#print axioms MI32.RawDirectionalActions.annihilationCoeff_nonneg
#print axioms MI32.RawDirectionalActions.annihilation_section_eq
#print axioms MI32.RawDirectionalActions.coefficient_annihilation
#print axioms MI32.RawDirectionalActions.coefficient_creation
#print axioms MI32.RawDirectionalActions.creationCoeff_nonneg
#print axioms MI32.RawDirectionalActions.creation_section_eq
#print axioms MI32.RawDirectionalActions.degree_actionExponent
#print axioms MI32.RawDirectionalActions.degree_actionExponent_le
#print axioms MI32.RawDirectionalActions.evaluate_annihilation_signed
#print axioms MI32.RawDirectionalActions.evaluate_creation_signed
#print axioms MI32.RawDirectionalActions.evaluate_product_split
#print axioms MI32.RawDirectionalActions.parity_actionExponent
#print axioms MI32.RawSectorNorms.annihilationCoeff_eq_zero_outside_support
#print axioms MI32.RawSectorNorms.annihilation_sectorAction_eq_restrict
#print axioms MI32.RawSectorNorms.creation_sectorAction_eq
#print axioms MI32.RawSectorNorms.norm_raw_annihilation_eq_sectorAction
#print axioms MI32.RawSectorNorms.zeroExtend_annihilation_sectorAction
#print axioms MI32.RestrictedThinMatrix.cols_moment_four_mul_le
#print axioms MI32.RestrictedThinMatrix.independent_restrict_rows
#print axioms MI32.RestrictedThinMatrix.independent_transposed_cols
#print axioms MI32.RestrictedThinMatrix.rows_moment_four_mul_le
#print axioms MI32.SupportedPolynomialInteraction.action_l2_le
#print axioms MI32.SupportedPolynomialInteraction.action_restrict_rows
#print axioms MI32.SupportedPolynomialInteraction.norm_evaluateHilbert_restrict
#print axioms MI32.SupportedPolynomialInteraction.zeroExtend_evaluateHilbert
#print axioms MI32.ThinMatrix.matrixRowImage_moment_four_mul_le
#print axioms MI32.ThinMatrix.transposeOperator_moment_four_mul_le
#print axioms MI32.ThinPolynomialInteraction.action_l2_le
#print axioms MI32.ThinPolynomialInteraction.same_entries_action_l2_le
#print axioms MI32.ThinTranspose.norm_transposeOperator_transpose
#print axioms MI32.ThinTranspose.output_cols_moment_four_mul_le
#print axioms MI32.ThinTranspose.transposeOperator_transpose_eq_adjoint

-- Original-law thin actions, exact raw sectors, and their contractions.
#print axioms MI32.PolynomialEnergyAssembly.commonLabelCover_card_le
#print axioms MI32.PolynomialEnergyAssembly.mem_commonLabelCover_in
#print axioms MI32.PolynomialEnergyAssembly.mem_commonLabelCover_out
#print axioms MI32.PolynomialEnergyAssembly.second_energy_le
#print axioms MI32.PolynomialEnergyAssembly.second_moment_le
#print axioms MI32.PolynomialEnergyAssembly.second_moment_le_of_all_sectors

-- Original-law thin actions, exact raw sectors, and their contractions.
#print axioms MI32.BipartiteConeContraction.action_apply_inl
#print axioms MI32.BipartiteConeContraction.action_apply_inr
#print axioms MI32.BipartiteConeContraction.action_eq_matrix_mulVec
#print axioms MI32.BipartiteConeContraction.action_inl_eq
#print axioms MI32.BipartiteConeContraction.action_inr_eq
#print axioms MI32.BipartiteConeContraction.action_l2_le
#print axioms MI32.BipartiteConeContraction.action_norm_sq_eq
#print axioms MI32.BipartiteConeContraction.action_vacuum_eq
#print axioms MI32.BipartiteConeContraction.polynomial_norm_sq_eq
#print axioms MI32.BipartiteNorm.bipartite_isSelfAdjoint
#print axioms MI32.BipartiteNorm.measurable_bipartite_norm
#print axioms MI32.BipartiteNorm.measurable_rectangular_norm
#print axioms MI32.BipartiteNorm.rectangular_norm_le_bipartite
#print axioms MI32.BipartiteVacuumIteration.vacuum_energies
#print axioms MI32.BipartiteVacuumIteration.vacuum_eq_matrix_power
#print axioms MI32.BipartiteVacuumIteration.vacuum_l2_le
#print axioms MI32.BipartiteVacuumIteration.vacuum_succ
#print axioms MI32.BipartiteVacuumIteration.vacuum_zero
#print axioms MI32.LocalSymmetricMoment.moment_rectangular_le_bipartite
#print axioms MI32.LocalSymmetricMoment.operator_moment_le
#print axioms MI32.PositiveVacuumWords.bipartiteWeight_nonneg
#print axioms MI32.PositiveVacuumWords.bipartite_matrix_inl_inl
#print axioms MI32.PositiveVacuumWords.bipartite_matrix_inl_inr
#print axioms MI32.PositiveVacuumWords.bipartite_matrix_inr_inl
#print axioms MI32.PositiveVacuumWords.bipartite_matrix_inr_inr
#print axioms MI32.PositiveVacuumWords.bipartite_matrix_transpose
#print axioms MI32.PositiveVacuumWords.card_term
#print axioms MI32.PositiveVacuumWords.coeff_nonneg
#print axioms MI32.PositiveVacuumWords.coeff_succ
#print axioms MI32.PositiveVacuumWords.coeff_zero
#print axioms MI32.PositiveVacuumWords.degree_exponent
#print axioms MI32.PositiveVacuumWords.evaluateHilbert_eq_pow_mulVec
#print axioms MI32.PositiveVacuumWords.evaluate_eq_pow_entry
#print axioms MI32.PositiveVacuumWords.evaluate_eq_pow_mulVec
#print axioms MI32.PositiveVacuumWords.evaluate_succ
#print axioms MI32.PositiveVacuumWords.evaluate_zero
#print axioms MI32.PositiveVacuumWords.exponent_succ
#print axioms MI32.PositiveVacuumWords.exponent_zero
#print axioms MI32.RawAnnihilatorContraction.annihilator_l2_le
#print axioms MI32.RawAnnihilatorContraction.input_mask_eq_zero_of_degree_lt
#print axioms MI32.RawCreatorContraction.creator_l2_le
#print axioms MI32.RawMultiplicationContraction.action_eq_creation_add_annihilation
#print axioms MI32.RawMultiplicationContraction.action_l2_le
#print axioms MI32.RawMultiplicationContraction.vector_sum_l2_le
#print axioms MI32.TransposedPolynomialContraction.action_l2_le
#print axioms MI32.VacuumNormBound.action_norm_le_sqrt_basis_energy
#print axioms MI32.VacuumNormBound.integral_norm_even_pow_le_vacuum_sum
#print axioms MI32.VacuumNormBound.norm_even_pow_le_vacuum_sum
#print axioms MI32.VacuumNormBound.norm_moment_le_of_vacuum_energies
#print axioms MI32.VacuumNormBound.norm_pow_of_selfAdjoint
#print axioms MI32.VacuumNormBound.opNorm_sq_le_basis_energy
#print axioms MI32.VacuumNormBound.sum_vacuum_norm_sq_eq_trace

-- Checked original-law analytic endpoints and exact reduction steps.
#print axioms MI32.BipartiteWeakMoment.bilinear_moment_le_norms
#print axioms MI32.BipartiteWeakMoment.bilinear_smul
#print axioms MI32.BipartiteWeakMoment.cross_norm_parts_le
#print axioms MI32.BipartiteWeakMoment.lift_bilinear_eq
#print axioms MI32.BipartiteWeakMoment.lift_bilinear_left_right
#print axioms MI32.BipartiteWeakMoment.lift_unit_test_moment_le
#print axioms MI32.BipartiteWeakMoment.memLp_bilinear
#print axioms MI32.BipartiteWeakMoment.norm_sq_parts
#print axioms MI32.BlockDiagonalMoment.integrable_and_mean_norm_le
#print axioms MI32.BlockDiagonalMoment.measurable_blockDiagonal_norm
#print axioms MI32.BlockDiagonalNorm.norm_blockDiagonal_le
#print axioms MI32.BlockDiagonalNorm.norm_blockDiagonal_le_max
#print axioms MI32.BlockDiagonalNorm.norm_sq_eq_sum_sections
#print axioms MI32.BlockDiagonalNorm.section_matrixOperator_blockDiagonal
#print axioms MI32.BlockMomentMaximum.geometric_weights_le_one
#print axioms MI32.BlockMomentMaximum.mean_max_le
#print axioms MI32.BlockMomentMaximum.scalar_le_threshold_add_power
#print axioms MI32.BlockMomentMaximum.tail_term_eq
#print axioms MI32.CopyDeletionScale.budget_minimum_copy_le
#print axioms MI32.CopyDeletionScale.deletedBilinear_copy_eq
#print axioms MI32.CopyDeletionScale.deletionScale_copy_le
#print axioms MI32.CopyDeletionScale.exists_same_set_budget_comparison
#print axioms MI32.CopyDeletionScale.test_moment_copy_le_exp
#print axioms MI32.CopyDeletionScale.weakMoment_copy_le
#print axioms MI32.DeletionMomentEndpoints.centered_moment_le_copy
#print axioms MI32.DeletionMomentEndpoints.copy_integral_le_two_of_le_one
#print axioms MI32.DeletionMomentEndpoints.copy_moment_le_exp
#print axioms MI32.DeletionMomentEndpoints.copy_moment_le_two
#print axioms MI32.DeletionMomentEndpoints.copy_moment_le_two_rpow_of_le_one
#print axioms MI32.DeletionMomentEndpoints.integrable_copy_abs_rpow
#print axioms MI32.DeletionMomentEndpoints.mean_zero_moment_le_copy
#print axioms MI32.DeletionMomentEndpoints.moment_copy_fst
#print axioms MI32.DeletionMomentEndpoints.moment_copy_snd
#print axioms MI32.DeletionVarianceSelection.card_largeRows_le
#print axioms MI32.DeletionVarianceSelection.card_selection_le
#print axioms MI32.DeletionVarianceSelection.exists_selection
#print axioms MI32.DeletionVarianceSelection.exists_variance_selection
#print axioms MI32.DeletionVarianceSelection.largeRows_subset_selection
#print axioms MI32.DeletionVarianceSelection.mem_largeRows
#print axioms MI32.DeletionVarianceSelection.selection_mono
#print axioms MI32.DeletionVarianceSelection.selection_zero
#print axioms MI32.DeletionVarianceSelection.selection_zero_budget
#print axioms MI32.DeletionVarianceSelection.subset_selection
#print axioms MI32.DeletionVarianceSelection.surviving_entry_le
#print axioms MI32.DeletionVarianceSelection.surviving_entry_le_div
#print axioms MI32.GeneralLawCopy.entry_symmetric
#print axioms MI32.GeneralLawCopy.integrable_entry
#print axioms MI32.GeneralLawCopy.integral_copy_entry_sq
#print axioms MI32.GeneralLawCopy.matrixCopy_apply
#print axioms MI32.GeneralLawCopy.regular_entries
#print axioms MI32.GeneralLawCopy.spectral_mean_le_copy
#print axioms MI32.LocalLogMoment.bilinear_eq_deletedBilinear_empty
#print axioms MI32.LocalLogMoment.bilinear_moment_le_eight
#print axioms MI32.LocalLogMoment.dimension_factor_le_exp
#print axioms MI32.LocalLogMoment.half_le_log_dimension
#print axioms MI32.LocalLogMoment.integrable_and_mean_le_even_moment
#print axioms MI32.LocalLogMoment.linearForm_eq_bilinear
#print axioms MI32.LocalLogMoment.log_two_le_log_dimension
#print axioms MI32.LocalLogMoment.meanConstant_nonneg
#print axioms MI32.LocalLogMoment.mean_spectralNorm_le
#print axioms MI32.LocalLogMoment.mean_spectralNorm_le_literal
#print axioms MI32.LocalLogMoment.one_le_momentOrder
#print axioms MI32.LocalLogMoment.twice_momentOrder_le_eight_log
#print axioms MI32.MatrixCopySymmetrization.independent_differences
#print axioms MI32.MatrixCopySymmetrization.integrable_difference_abs_rpow
#print axioms MI32.MatrixCopySymmetrization.integrable_operator
#print axioms MI32.MatrixCopySymmetrization.integral_difference
#print axioms MI32.MatrixCopySymmetrization.integral_difference_sq
#print axioms MI32.MatrixCopySymmetrization.integral_norm_le_copy
#print axioms MI32.MatrixCopySymmetrization.integral_operator_zero
#print axioms MI32.MatrixCopySymmetrization.measurable_difference
#print axioms MI32.MatrixCopySymmetrization.norm_operatorMap
#print axioms MI32.MatrixCopySymmetrization.spectral_mean_le_copy
#print axioms MI32.MatrixCopySymmetrization.symmetric_difference
#print axioms MI32.SymmetricLinearAllOrders.integral_two_pow_seven_le
#print axioms MI32.SymmetricLinearAllOrders.linear_integrable_and_root_doubling
#print axioms MI32.SymmetricLinearAllOrders.linear_root_doubling
#print axioms MI32.SymmetricLinearAllOrders.moment_two_le_half
#print axioms MI32.SymmetricLinearAllOrders.one_le_doublingConstant
#print axioms MI32.SymmetricLinearAllOrders.real_doubling_of_even_doubling
#print axioms MI32.SymmetrizationReduction.deletionScale_copy
#print axioms MI32.SymmetrizationReduction.upperBoundAt_of_symmetric
#print axioms MI32.SymmetrizationReduction.varianceScale_copy
#print axioms MI32.VarianceScaleBasics.colStd_le_varianceScale
#print axioms MI32.VarianceScaleBasics.col_variance_le_sq
#print axioms MI32.VarianceScaleBasics.finite_sup_mul
#print axioms MI32.VarianceScaleBasics.finite_sup_nonneg
#print axioms MI32.VarianceScaleBasics.rowStd_le_varianceScale
#print axioms MI32.VarianceScaleBasics.row_variance_le_sq
#print axioms MI32.VarianceScaleBasics.varianceScale_eq
#print axioms MI32.VarianceScaleBasics.varianceScale_nonneg
#print axioms MI32.VarianceScaleBasics.varianceScale_of_entry_second_moments
#print axioms MI32.WeakMomentBasics.abs_deletedBilinear_le_entryAbsSum
#print axioms MI32.WeakMomentBasics.budget_minimum_nonneg
#print axioms MI32.WeakMomentBasics.budget_value_set_finite
#print axioms MI32.WeakMomentBasics.deletionScale_nonneg
#print axioms MI32.WeakMomentBasics.deletion_value_set_finite
#print axioms MI32.WeakMomentBasics.exists_deletion_minimizer_le_scale
#print axioms MI32.WeakMomentBasics.exists_minimizing_set
#print axioms MI32.WeakMomentBasics.integrable_deletedBilinear_abs_rpow
#print axioms MI32.WeakMomentBasics.memLp_entryAbsSum
#print axioms MI32.WeakMomentBasics.minimum_le_deletionScale
#print axioms MI32.WeakMomentBasics.moment_deletedBilinear_le_entryAbsSum
#print axioms MI32.WeakMomentBasics.moment_le_weakMoment
#print axioms MI32.WeakMomentBasics.weakMoment_full_deletion_eq_zero
#print axioms MI32.WeakMomentBasics.weakMoment_le_entryAbsSum
#print axioms MI32.WeakMomentBasics.weakMoment_nonneg
#print axioms MI32.WeakMomentBasics.weak_test_set_bddAbove

-- Deletion-chain endpoints added with the completed symmetric deletion theorem.
#print axioms MI32.BilinearHighOrder.bilinear_moment_doubling
#print axioms MI32.BilinearHighOrder.bilinear_moment_doubling_pow
#print axioms MI32.BilinearHighOrder.bilinear_moment_le_pow
#print axioms MI32.BlockMaskMoment.integrable_of_integrable_pow
#print axioms MI32.BlockMaskMoment.mean_norm_le_of_block_moments
#print axioms MI32.BlockMaskMoment.measurable_blockSub_norm
#print axioms MI32.BlockMaskMoment.measurable_norm
#print axioms MI32.BlockOrderArithmetic.blockOrder_lt
#print axioms MI32.BlockOrderArithmetic.dimension_factor_le_exp
#print axioms MI32.BlockOrderArithmetic.half_lt_log_two
#print axioms MI32.BlockOrderArithmetic.index_add_two_le_pow
#print axioms MI32.BlockOrderArithmetic.index_add_two_le_two_blockOrder
#print axioms MI32.BlockOrderArithmetic.log_two_lt_one
#print axioms MI32.BlockOrderArithmetic.one_le_blockOrder
#print axioms MI32.BlockOrderArithmetic.pow_succ_le_pow_sub_two
#print axioms MI32.BlockOrderArithmetic.two_blockOrder_le
#print axioms MI32.BlockOrderArithmetic.two_order_le_blockOrder
#print axioms MI32.CenteredGramNorm.entryEnergy_nonneg
#print axioms MI32.CenteredGramNorm.gram_mean_le
#print axioms MI32.CenteredGramNorm.mean_le_of_second_moment
#print axioms MI32.CenteredGramNorm.mean_norm_le
#print axioms MI32.CenteredGramNorm.norm_diagonal_le
#print axioms MI32.CenteredGramNorm.norm_sq_le_diagonal_add_centeredGram
#print axioms MI32.CenteredGramNorm.norm_sq_le_entryEnergy
#print axioms MI32.DeletionMasks.blockSub_nearCross_eq
#print axioms MI32.DeletionMasks.blockSub_nearCross_zero
#print axioms MI32.DeletionMasks.blockSub_nearHigh_eq
#print axioms MI32.DeletionMasks.blockSub_nearHigh_zero
#print axioms MI32.DeletionMasks.cEven_eq_iff
#print axioms MI32.DeletionMasks.cEven_eq_zero_iff
#print axioms MI32.DeletionMasks.cEven_fiber_label
#print axioms MI32.DeletionMasks.cOdd_eq_iff
#print axioms MI32.DeletionMasks.cOdd_eq_zero_iff
#print axioms MI32.DeletionMasks.cOdd_fiber_label
#print axioms MI32.DeletionMasks.entry_sum
#print axioms MI32.DeletionMasks.farLow_eq_masked
#print axioms MI32.DeletionMasks.farUp_eq_masked_transpose
#print axioms MI32.DeletionMasks.label_le_iff
#print axioms MI32.DeletionMasks.label_lt
#print axioms MI32.DeletionMasks.matrix_sum
#print axioms MI32.DeletionMasks.nearCross_fiber_supported
#print axioms MI32.DeletionMasks.nearEven_split
#print axioms MI32.DeletionMasks.nearHigh_fiber_supported
#print axioms MI32.DeletionMasks.nearLow_support
#print axioms MI32.DeletionMasks.norm_blockSub_nearCross_le
#print axioms MI32.DeletionMasks.norm_le_masks
#print axioms MI32.DeletionMasks.val_cEven
#print axioms MI32.DeletionMasks.val_cOdd
#print axioms MI32.DeletionScheduleArithmetic.budget_add_one
#print axioms MI32.DeletionScheduleArithmetic.budget_ge_two_pow
#print axioms MI32.DeletionScheduleArithmetic.budget_pos
#print axioms MI32.DeletionScheduleArithmetic.budget_strictMono
#print axioms MI32.DeletionScheduleArithmetic.budget_succ
#print axioms MI32.DeletionScheduleArithmetic.budget_zero
#print axioms MI32.DeletionScheduleArithmetic.finite_terminal_bound
#print axioms MI32.DeletionScheduleArithmetic.log_two_le_order
#print axioms MI32.DeletionScheduleArithmetic.order_add
#print axioms MI32.DeletionScheduleArithmetic.order_eq
#print axioms MI32.DeletionScheduleArithmetic.order_pos
#print axioms MI32.DeletionScheduleArithmetic.order_succ
#print axioms MI32.DeletionScheduleArithmetic.order_zero
#print axioms MI32.DeletionScheduleArithmetic.size_ge_two
#print axioms MI32.DeletionScheduleArithmetic.size_pos
#print axioms MI32.DeletionScheduleArithmetic.size_succ
#print axioms MI32.DeletionScheduleArithmetic.step_card_le
#print axioms MI32.FarMaskMean.card_columnsThrough_le
#print axioms MI32.FarMaskMean.independent_transposed
#print axioms MI32.FarMaskMean.mean_farLow_le
#print axioms MI32.FarMaskMean.mean_farUp_le
#print axioms MI32.FarRemainderMoment.gram_scale_sq
#print axioms MI32.FarRemainderMoment.mean_norm_le_of_graded
#print axioms MI32.FarRemainderMoment.norm_transpose_eq
#print axioms MI32.FarRemainderMoment.sqrt_scale_eq
#print axioms MI32.FiberBlockNorm.blockSub_apply
#print axioms MI32.FiberBlockNorm.fiberSection_matrixOperator
#print axioms MI32.FiberBlockNorm.fiber_supported_of_mask
#print axioms MI32.FiberBlockNorm.norm_le_of_fiber_supported
#print axioms MI32.FiberBlockNorm.norm_le_pi_blockSub
#print axioms MI32.FiberBlockNorm.norm_offDiagonal_le
#print axioms MI32.FiberBlockNorm.norm_sq_eq_sum_fiberSections
#print axioms MI32.FiberBlockNorm.offDiagonal_entry_eq
#print axioms MI32.FrobeniusMean.entryEnergy_nonneg
#print axioms MI32.FrobeniusMean.integrable_and_mean_norm_le
#print axioms MI32.FrobeniusMean.mean_norm_le_of_row_budget
#print axioms MI32.FrobeniusMean.norm_image_sq_le
#print axioms MI32.FrobeniusMean.norm_le_sqrt_entryEnergy
#print axioms MI32.FrobeniusMean.norm_sq_le_entryEnergy
#print axioms MI32.GradedVarianceEnergy.budget_ratio_le_reciprocal
#print axioms MI32.GradedVarianceEnergy.budget_ratio_sum_le_two
#print axioms MI32.GradedVarianceEnergy.card_columnPairsAt_le
#print axioms MI32.GradedVarianceEnergy.columnPairsAt_subset
#print axioms MI32.GradedVarianceEnergy.pair_energy_le
#print axioms MI32.GradedVarianceEnergy.pair_energy_le_of_label_le
#print axioms MI32.GradedVarianceEnergy.sum_pair_weights_eq
#print axioms MI32.GradedVarianceEnergy.total_energy_le
#print axioms MI32.GradedVarianceEnergy.total_energy_le_two
#print axioms MI32.GramEntryMoments.centeredGram_apply
#print axioms MI32.GramEntryMoments.centeredGram_apply_diag
#print axioms MI32.GramEntryMoments.centeredGram_apply_offdiag
#print axioms MI32.GramEntryMoments.centeredGram_entry
#print axioms MI32.GramEntryMoments.entry_memLp
#print axioms MI32.GramEntryMoments.entry_memLp_four
#print axioms MI32.GramEntryMoments.entry_memLp_two
#print axioms MI32.GramEntryMoments.indepFun_centered_sq_rows
#print axioms MI32.GramEntryMoments.indepFun_prod_rows
#print axioms MI32.GramEntryMoments.independent_rows
#print axioms MI32.GramEntryMoments.integrable_centeredGram_sq
#print axioms MI32.GramEntryMoments.integrable_pow_four
#print axioms MI32.GramEntryMoments.integrable_sq
#print axioms MI32.GramEntryMoments.integral_centeredGram_sq_le
#print axioms MI32.GramEntryMoments.integral_centered_square_sum_sq
#print axioms MI32.GramEntryMoments.integral_column_product_sq
#print axioms MI32.GramEntryMoments.integral_prod_eq
#print axioms MI32.GramEntryMoments.integral_prod_sq_eq
#print axioms MI32.GramEntryMoments.integral_sub_mean_sq
#print axioms MI32.GramEntryMoments.memLp_centeredGram_two
#print axioms MI32.GramEntryMoments.prod_memLp_two
#print axioms MI32.GramEntryMoments.sq_memLp_two
#print axioms MI32.GramEntryMoments.total_centeredGram_energy_le
#print axioms MI32.MaskedEntryLaw.abs_masked_le
#print axioms MI32.MaskedEntryLaw.independent_masked
#print axioms MI32.MaskedEntryLaw.integrable_masked_abs_rpow
#print axioms MI32.MaskedEntryLaw.integral_fourth_le_of_regular
#print axioms MI32.MaskedEntryLaw.integral_fourth_masked_le
#print axioms MI32.MaskedEntryLaw.integral_masked_eq_zero
#print axioms MI32.MaskedEntryLaw.integral_sq_masked_eq_zero_of_not
#print axioms MI32.MaskedEntryLaw.integral_sq_masked_le
#print axioms MI32.MaskedEntryLaw.integral_sq_masked_nonneg
#print axioms MI32.MaskedEntryLaw.mask_of_integral_sq_masked_ne_zero
#print axioms MI32.MaskedEntryLaw.masked_apply_false
#print axioms MI32.MaskedEntryLaw.masked_apply_true
#print axioms MI32.MaskedEntryLaw.masked_eq_of_true
#print axioms MI32.MaskedEntryLaw.masked_eq_zero_of_false
#print axioms MI32.MaskedEntryLaw.masked_sq_le
#print axioms MI32.MaskedEntryLaw.measurable_masked
#print axioms MI32.MaskedEntryLaw.moment_zero_fun
#print axioms MI32.MaskedEntryLaw.regular_masked
#print axioms MI32.MaskedEntryLaw.sum_col_sq_masked_le
#print axioms MI32.MaskedEntryLaw.sum_row_sq_masked_le
#print axioms MI32.MaskedEntryLaw.symmetric_masked
#print axioms MI32.NearBlockMoment.blockBound_nonneg
#print axioms MI32.NearBlockMoment.block_integral_pow_le
#print axioms MI32.NearBlockMoment.block_moment_le
#print axioms MI32.NearBlockMoment.doublingConstant_nonneg
#print axioms MI32.NearBlockMoment.integral_pow_le_of_dominated
#print axioms MI32.NearMaskMean.budget_one
#print axioms MI32.NearMaskMean.integrable_sq_nearLow
#print axioms MI32.NearMaskMean.integral_sq_nearLow_le
#print axioms MI32.NearMaskMean.mean_mask_le
#print axioms MI32.NearMaskMean.mean_nearCross_le
#print axioms MI32.NearMaskMean.mean_nearHigh_le
#print axioms MI32.NearMaskMean.mean_nearLow_le
#print axioms MI32.NearMaskMean.measurable_nearCross
#print axioms MI32.NearMaskMean.measurable_nearHigh
#print axioms MI32.NearMaskMean.measurable_nearLow
#print axioms MI32.NestedDeletionFamily.card_filter_level_le
#print axioms MI32.NestedDeletionFamily.card_sets_le
#print axioms MI32.NestedDeletionFamily.column_screen
#print axioms MI32.NestedDeletionFamily.level_le_iff
#print axioms MI32.NestedDeletionFamily.row_screen
#print axioms MI32.NestedDeletionFamily.sets_horizon_eq_univ
#print axioms MI32.NestedDeletionFamily.sets_mono
#print axioms MI32.NestedDeletionFamily.sets_succ
#print axioms MI32.NestedDeletionFamily.sets_zero
#print axioms MI32.NestedDeletionFamily.weak_screen
#print axioms MI32.NestedShells.cumulative_card_eq
#print axioms MI32.NestedShells.cumulative_eq
#print axioms MI32.NestedShells.entry_partition
#print axioms MI32.NestedShells.exists_unique_shell
#print axioms MI32.NestedShells.farLower_common_support
#print axioms MI32.NestedShells.farLower_nonzero
#print axioms MI32.NestedShells.farLower_nonzero_outside
#print axioms MI32.NestedShells.farUpper_eq_transpose_farLower
#print axioms MI32.NestedShells.level_le_iff
#print axioms MI32.NestedShells.level_le_of_mem
#print axioms MI32.NestedShells.mem_level
#print axioms MI32.NestedShells.mem_of_level_le
#print axioms MI32.NestedShells.mem_own_shell
#print axioms MI32.NestedShells.near_iff
#print axioms MI32.NestedShells.near_masks_disjoint
#print axioms MI32.NestedShells.shell_disjoint
#print axioms MI32.NestedShells.shell_succ
#print axioms MI32.NestedShells.shell_zero
#print axioms MI32.RestrictedBlockFamily.bilinear_blockEntries_eq_deletedBilinear
#print axioms MI32.RestrictedBlockFamily.blockEntries_apply
#print axioms MI32.RestrictedBlockFamily.col_budget_blockEntries
#print axioms MI32.RestrictedBlockFamily.fiberExtend_apply_of_eq
#print axioms MI32.RestrictedBlockFamily.fiberExtend_apply_of_ne
#print axioms MI32.RestrictedBlockFamily.independent_blockEntries
#print axioms MI32.RestrictedBlockFamily.integrable_blockEntries
#print axioms MI32.RestrictedBlockFamily.measurable_blockEntries
#print axioms MI32.RestrictedBlockFamily.moment_bilinear_blockEntries_le_weakMoment
#print axioms MI32.RestrictedBlockFamily.norm_fiberExtend
#print axioms MI32.RestrictedBlockFamily.rectangular_blockEntries
#print axioms MI32.RestrictedBlockFamily.regular_blockEntries
#print axioms MI32.RestrictedBlockFamily.row_budget_blockEntries
#print axioms MI32.RestrictedBlockFamily.sum_fiber_dite
#print axioms MI32.RestrictedBlockFamily.symmetric_blockEntries
#print axioms MI32.SymmetricDeletion.deletionCoeff_nonneg
#print axioms MI32.SymmetricDeletion.deletionConstant_pos
#print axioms MI32.SymmetricDeletion.exists_upperBoundAt
#print axioms MI32.SymmetricDeletion.five_masks_le
#print axioms MI32.SymmetricDeletion.integrable_and_mean_spectralNorm_le
#print axioms MI32.SymmetricDeletion.symmetricUpperBoundAt
#print axioms MI32.SymmetricDeletion.upperBoundAt
#print axioms MI32.SymmetricDeletion.varianceCoeff_pos
#print axioms MI32.WeakDeletionMonotonicity.deletedBilinear_mask
#print axioms MI32.WeakDeletionMonotonicity.mask_apply_mem
#print axioms MI32.WeakDeletionMonotonicity.mask_apply_not_mem
#print axioms MI32.WeakDeletionMonotonicity.norm_mask_le
#print axioms MI32.WeakDeletionMonotonicity.norm_mask_sq
#print axioms MI32.WeakDeletionMonotonicity.weakMoment_antitone
#print axioms MI32.WeakDeletionMonotonicity.weakMoment_le_of_subset_of_order
#print axioms MI32.WeakDeletionMonotonicity.weakMoment_mono_order

-- Non-vacuity witness for the source hypothesis class.
#print axioms MI32.RegularWitness.abs_sign
#print axioms MI32.RegularWitness.abs_sign_rpow
#print axioms MI32.RegularWitness.coe_half
#print axioms MI32.RegularWitness.exists_regularEntries
#print axioms MI32.RegularWitness.independent_entries
#print axioms MI32.RegularWitness.integrable_entry_abs_rpow
#print axioms MI32.RegularWitness.integral_coordinate
#print axioms MI32.RegularWitness.integral_entry
#print axioms MI32.RegularWitness.integral_entry_sq
#print axioms MI32.RegularWitness.integral_sign
#print axioms MI32.RegularWitness.measurable_entry
#print axioms MI32.RegularWitness.measurable_sign
#print axioms MI32.RegularWitness.moment_entry
#print axioms MI32.RegularWitness.regularEntries_signMatrix
#print axioms MI32.RegularWitness.regular_entry
#print axioms MI32.RegularWitness.rowStd_signMatrix
#print axioms MI32.RegularWitness.signMatrix_apply
#print axioms MI32.RegularWitness.sign_sq
#print axioms MI32.RegularWitness.varianceScale_pos
