import MI32.Statement
import MI32.StatementChecks
import MI32.MomentDoubling
import MI32.PositivePolynomial
import MI32.RegularPositivePolynomial
import MI32.HilbertWalsh
import MI32.ParityGeometry
import MI32.PositiveCone
import MI32.RegularPositiveCone
import MI32.RawParity
import MI32.RawPositiveCone
import MI32.ConeInterpolation
import MI32.SymmetricLaw
import MI32.FiniteNet
import MI32.ThinNetMoment
import MI32.MatrixImages
import MI32.SymmetricPositiveCone
import MI32.PositiveLinearPowers
import MI32.PositiveMomentComparison
import MI32.SymmetricMomentComparison
import MI32.CopySymmetrization
import MI32.HilbertConditioning
import MI32.IndependentColumns
import MI32.DiagonalCopyComparison
import MI32.MomentTools
import MI32.SymmetricLinearRegularity
import MI32.HilbertComparison
import MI32.ThinMomentRoot
import MI32.SymmetricConeInterpolation

import MI32.ActiveCountSectors
import MI32.AnnihilationSectorContraction
import MI32.AxisRestriction
import MI32.CreationSectorContraction
import MI32.MaskedPolynomialAction
import MI32.MultiplicationHolder
import MI32.OutputPolynomialInteraction
import MI32.ParityWalshCompression
import MI32.PolynomialEnergyAssembly
import MI32.PolynomialSectorEnergy
import MI32.PolynomialSectorMasks
import MI32.PositiveWordExtension
import MI32.RawCountBlocks
import MI32.RawDirectionalActions
import MI32.RawSectorNorms
import MI32.RestrictedThinMatrix
import MI32.SupportedPolynomialInteraction
import MI32.ThinMatrix
import MI32.ThinPolynomialInteraction
import MI32.ThinTranspose

import MI32.BipartiteConeContraction
import MI32.BipartiteNorm
import MI32.BipartiteVacuumIteration
import MI32.LocalSymmetricMoment
import MI32.PositiveVacuumWords
import MI32.RawAnnihilatorContraction
import MI32.RawCreatorContraction
import MI32.RawMultiplicationContraction
import MI32.TransposedPolynomialContraction
import MI32.VacuumNormBound

import MI32.BipartiteWeakMoment
import MI32.BlockDiagonalMoment
import MI32.BlockDiagonalNorm
import MI32.BlockMomentMaximum
import MI32.CopyDeletionScale
import MI32.DeletionMomentEndpoints
import MI32.DeletionVarianceSelection
import MI32.GeneralLawCopy
import MI32.LocalLogMoment
import MI32.MatrixCopySymmetrization
import MI32.SymmetricLinearAllOrders
import MI32.SymmetrizationReduction
import MI32.VarianceScaleBasics
import MI32.WeakMomentBasics

import MI32.CenteredGramNorm
import MI32.DeletionScheduleArithmetic
import MI32.GradedVarianceEnergy
import MI32.NestedShells
import MI32.WeakDeletionMonotonicity
import MI32.NestedDeletionSelection

import MI32.BilinearHighOrder
import MI32.BlockOrderArithmetic
import MI32.FiberBlockNorm
import MI32.FrobeniusMean
import MI32.GramEntryMoments
import MI32.MaskedEntryLaw
import MI32.NestedDeletionFamily
import MI32.RestrictedBlockFamily
import MI32.BlockMaskMoment
import MI32.FarRemainderMoment
import MI32.NearBlockMoment
import MI32.DeletionMasks
import MI32.NearMaskMean
import MI32.FarMaskMean
import MI32.SymmetricDeletion
import MI32.RegularWitness

/-! Completed proof core. This module imports neither Challenge nor Solution. -/
